#!/usr/bin/env python
from __future__ import annotations

import json
import subprocess
import sys
import time
from argparse import ArgumentParser
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import torch
from tqdm.auto import tqdm

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.analysis.humor_context import extract_json, get_model_device, load_qwen_vl
from src.utils.io import read_jsonl

DEFAULT_JUDGE_MODEL = "/home/zhang.jianqiao/models/Qwen2.5-VL-7B-Instruct"

PROMPT_TEMPLATE = """You are judging prompt/annotation methods for humorous image-caption generation.

You receive one image, its dataset gold caption, and candidate captions generated by several methods.
Your job is to decide which method produced the best candidate RELATIVE TO THE GOLD CAPTION'S HUMOR TARGET.

Judge by these rules:
- First infer why the gold caption is funny for this image.
- A candidate is better if it targets the same visual joke or a very close humor mechanism.
- Do not require exact wording, but penalize candidates that miss the gold joke target.
- Penalize captions that copy auxiliary wording, explain the joke, are generic, or are not grounded in the image.
- If no method has a candidate that reasonably matches the gold humor target, set best_method to "no_clear_match".

Return only valid JSON with this exact schema:
{
  "gold_humor_target": "short description of the gold caption's joke target",
  "best_method": "method name or no_clear_match",
  "best_candidate": "best caption text or empty string",
  "scores": {
    "method_name": {
      "gold_target_match": 1,
      "image_grounding": 1,
      "naturalness": 1,
      "format": 1,
      "overall": 1
    }
  },
  "reason": "short reason"
}

Scores are 1-5 integers. Score each method by its best candidate only.

Gold caption:
{gold_caption}

Candidates by method:
{candidate_block}
"""


def query_gpu_free_mb(gpu_index: int) -> int:
    result = subprocess.run(
        [
            "nvidia-smi",
            f"--id={gpu_index}",
            "--query-gpu=memory.free",
            "--format=csv,noheader,nounits",
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    return int(result.stdout.strip().splitlines()[0])


def wait_for_gpu_memory(min_free_mb: int, gpu_index: int, stable_checks: int, check_seconds: int) -> None:
    if min_free_mb <= 0:
        return
    stable = 0
    print(
        "[gold-judge] "
        f"waiting for gpu={gpu_index} free memory >= {min_free_mb} MiB "
        f"for {stable_checks} consecutive checks"
    )
    while stable < stable_checks:
        free_mb = query_gpu_free_mb(gpu_index)
        stable = stable + 1 if free_mb >= min_free_mb else 0
        print(f"[gold-judge] gpu={gpu_index} free_memory={free_mb} MiB stable={stable}/{stable_checks}")
        if stable < stable_checks:
            time.sleep(check_seconds)


def row_key(row: dict[str, Any]) -> str:
    if row.get("row_key"):
        return str(row["row_key"])
    return f"{row.get('image') or row.get('image_id')}::{row.get('gold_caption') or ''}"


def load_method_rows(paths: list[Path], max_candidates_per_method: int) -> dict[str, dict[str, Any]]:
    grouped: dict[str, dict[str, Any]] = {}
    for path in paths:
        for row in read_jsonl(path):
            method = str(row.get("method") or path.stem)
            candidates = [str(candidate).strip() for candidate in row.get("candidates") or [] if str(candidate).strip()]
            if not candidates:
                continue
            key = row_key(row)
            item = grouped.setdefault(
                key,
                {
                    "row_key": key,
                    "image": row.get("image"),
                    "image_id": row.get("image_id"),
                    "gold_caption": row.get("gold_caption"),
                    "methods": {},
                },
            )
            item["methods"][method] = candidates[:max_candidates_per_method]
    return grouped


def existing_keys(path: Path) -> set[str]:
    if not path.exists():
        return set()
    keys = set()
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if row.get("row_key"):
                keys.add(str(row["row_key"]))
    return keys


def append_jsonl(path: Path, row: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(row, ensure_ascii=False) + "\n")
        handle.flush()


def clamp_score(value: Any) -> int:
    try:
        score = int(round(float(value)))
    except (TypeError, ValueError):
        return 0
    return max(0, min(5, score))


def normalize_judgment(value: dict[str, Any], methods: dict[str, list[str]]) -> dict[str, Any]:
    best_method = str(value.get("best_method") or "no_clear_match")
    if best_method not in methods and best_method != "no_clear_match":
        best_method = "no_clear_match"
    raw_scores = value.get("scores") if isinstance(value.get("scores"), dict) else {}
    scores = {}
    for method in methods:
        method_scores = raw_scores.get(method) if isinstance(raw_scores.get(method), dict) else {}
        scores[method] = {
            "gold_target_match": clamp_score(method_scores.get("gold_target_match")),
            "image_grounding": clamp_score(method_scores.get("image_grounding")),
            "naturalness": clamp_score(method_scores.get("naturalness")),
            "format": clamp_score(method_scores.get("format")),
            "overall": clamp_score(method_scores.get("overall")),
        }
    return {
        "gold_humor_target": str(value.get("gold_humor_target") or "")[:500],
        "best_method": best_method,
        "best_candidate": str(value.get("best_candidate") or "")[:500],
        "scores": scores,
        "reason": str(value.get("reason") or "")[:300],
    }


def build_candidate_block(methods: dict[str, list[str]]) -> str:
    lines = []
    for method in sorted(methods):
        lines.append(f"Method: {method}")
        for index, candidate in enumerate(methods[method], start=1):
            clean = " ".join(str(candidate).split())
            lines.append(f"  {index}. {clean}")
    return "\n".join(lines)


def judge_one(
    model: Any,
    processor: Any,
    process_vision_info: Any,
    item: dict[str, Any],
    max_new_tokens: int,
) -> tuple[dict[str, Any], str]:
    prompt = PROMPT_TEMPLATE.replace(
        "{gold_caption}", " ".join(str(item.get("gold_caption") or "").split())
    ).replace("{candidate_block}", build_candidate_block(item["methods"]))
    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": str(item["image"])},
                {"type": "text", "text": prompt},
            ],
        }
    ]
    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    image_inputs, video_inputs = process_vision_info(messages)
    inputs = processor(text=[text], images=image_inputs, videos=video_inputs, padding=True, return_tensors="pt")
    inputs = inputs.to(get_model_device(model))
    with torch.no_grad():
        generated = model.generate(**inputs, do_sample=False, max_new_tokens=max_new_tokens)
    new_tokens = generated[:, inputs["input_ids"].shape[-1] :]
    decoded = processor.batch_decode(new_tokens, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0].strip()
    return extract_json(decoded), decoded


def write_summary(output_jsonl: Path, summary_json: Path, report_md: Path) -> None:
    rows = read_jsonl(output_jsonl) if output_jsonl.exists() else []
    scored = [row for row in rows if not row.get("judge_failed")]
    failures = [row for row in rows if row.get("judge_failed")]
    best_counts = Counter(row.get("best_method") for row in scored)
    methods = sorted({method for row in scored for method in (row.get("scores") or {})})

    def mean(values: list[float]) -> float:
        return sum(values) / len(values) if values else 0.0

    avg_scores = {}
    for method in methods:
        avg_scores[method] = {
            metric: mean([
                float(((row.get("scores") or {}).get(method) or {}).get(metric, 0))
                for row in scored
                if method in (row.get("scores") or {})
            ])
            for metric in ("gold_target_match", "image_grounding", "naturalness", "format", "overall")
        }
    summary = {
        "rows": len(rows),
        "scored_rows": len(scored),
        "failures": len(failures),
        "best_method_counts": dict(best_counts.most_common()),
        "avg_scores": avg_scores,
    }
    summary_json.parent.mkdir(parents=True, exist_ok=True)
    summary_json.write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    lines = [
        "# HIC Gold-Reference Guidance Method Judge",
        "",
        f"Rows: {summary['rows']}",
        f"Scored rows: {summary['scored_rows']}",
        f"Failures: {summary['failures']}",
        "",
        "## Best Method Counts",
        "",
        "| method | count |",
        "|---|---:|",
    ]
    for method, count in summary["best_method_counts"].items():
        lines.append(f"| {method} | {count} |")
    lines.extend(["", "## Average Scores", "", "| method | gold_match | grounding | naturalness | format | overall |", "|---|---:|---:|---:|---:|---:|"])
    for method, scores in sorted(avg_scores.items()):
        lines.append(
            f"| {method} | {scores['gold_target_match']:.2f} | {scores['image_grounding']:.2f} | "
            f"{scores['naturalness']:.2f} | {scores['format']:.2f} | {scores['overall']:.2f} |"
        )
    report_md.parent.mkdir(parents=True, exist_ok=True)
    report_md.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    print(f"[gold-judge] wrote {summary_json}")
    print(f"[gold-judge] wrote {report_md}")


def main() -> None:
    parser = ArgumentParser(description="Judge HIC guidance methods by gold-caption humor target match.")
    parser.add_argument("--generation-jsonl", type=Path, action="append", required=True)
    parser.add_argument("--output-jsonl", type=Path, default=Path("outputs/evaluations/hic_guidance_gold_judgments.jsonl"))
    parser.add_argument("--summary-json", type=Path, default=Path("outputs/evaluations/hic_guidance_gold_summary.json"))
    parser.add_argument("--report-md", type=Path, default=Path("outputs/evaluations/hic_guidance_gold_report.md"))
    parser.add_argument("--judge-model", default=DEFAULT_JUDGE_MODEL)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--min-methods", type=int, default=2)
    parser.add_argument("--max-candidates-per-method", type=int, default=8)
    parser.add_argument("--max-new-tokens", type=int, default=768)
    parser.add_argument("--device-map", default="auto")
    parser.add_argument("--torch-dtype", default="auto")
    parser.add_argument("--min-pixels", type=int, default=256 * 28 * 28)
    parser.add_argument("--max-pixels", type=int, default=1024 * 28 * 28)
    parser.add_argument("--wait-gpu-free-mb", type=int, default=0)
    parser.add_argument("--wait-gpu-index", type=int, default=0)
    parser.add_argument("--wait-gpu-stable-checks", type=int, default=3)
    parser.add_argument("--wait-gpu-check-seconds", type=int, default=60)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    grouped = [item for item in load_method_rows(args.generation_jsonl, args.max_candidates_per_method).values() if len(item["methods"]) >= args.min_methods]
    grouped.sort(key=lambda item: item["row_key"])
    if args.limit is not None:
        grouped = grouped[: args.limit]
    if args.overwrite and args.output_jsonl.exists():
        args.output_jsonl.unlink()
    done = existing_keys(args.output_jsonl) if args.resume else set()
    print(f"[gold-judge] rows={len(grouped)} already_done={len(done)}")

    wait_for_gpu_memory(
        min_free_mb=args.wait_gpu_free_mb,
        gpu_index=args.wait_gpu_index,
        stable_checks=args.wait_gpu_stable_checks,
        check_seconds=args.wait_gpu_check_seconds,
    )
    model, processor, process_vision_info = load_qwen_vl(
        model_name=args.judge_model,
        device_map=args.device_map,
        torch_dtype=args.torch_dtype,
        trust_remote_code=True,
        min_pixels=args.min_pixels,
        max_pixels=args.max_pixels,
    )

    for item in tqdm(grouped, desc="judging gold-reference methods", dynamic_ncols=True):
        if item["row_key"] in done:
            continue
        try:
            raw, raw_text = judge_one(model, processor, process_vision_info, item, max_new_tokens=args.max_new_tokens)
            normalized = normalize_judgment(raw, item["methods"])
            output = {
                "row_key": item["row_key"],
                "image": item.get("image"),
                "image_id": item.get("image_id"),
                "gold_caption": item.get("gold_caption"),
                "methods": sorted(item["methods"]),
                **normalized,
                "raw_judge_response": raw_text,
                "judge_failed": False,
                "error": "",
            }
        except Exception as exc:
            output = {
                "row_key": item["row_key"],
                "image": item.get("image"),
                "image_id": item.get("image_id"),
                "gold_caption": item.get("gold_caption"),
                "methods": sorted(item["methods"]),
                "best_method": "judge_failed",
                "best_candidate": "",
                "scores": {},
                "judge_failed": True,
                "error": repr(exc),
            }
            print(f"[gold-judge] failed {item['row_key']}: {exc}")
        append_jsonl(args.output_jsonl, output)
    write_summary(args.output_jsonl, args.summary_json, args.report_md)


if __name__ == "__main__":
    main()
